### ISSUE TITLE
Usar o servidor web de php en desenvolvemento local

### ISSUE THREAD

**Issue by oscarotero** [anavallasuiza/new-projects-template#6]
Actualmente para traballar nun proxecto en local precisas ter un servidor web rulando (normalmente Apache). Propoño usar o servidor que trae xa php por varios motivos:
- Non precisas ter apache instalado e configurado, nin ningún outro sofware, simplemente php.
- As urls serían iguais en todos os equipos (en vez de ter, por exemplo, `http://localhost/proxecto/public` nun lado e `http://proxecto.localhost` noutro ou `http://proxecto.local`.
- Non habería problemas de permisos de escritura (para logs, caché, etc), xa que o mesmo usuario co que fas git pull e editas o código, sería o que lanza o servidor.
- Cun só comando poderías lanzar o servidor, lanzar gulp, e poder ver xa a web no navegador, o que sería moito máis fácil para todo o mundo, e máis controlable polos programadores.
- Non faría falta o arquivo `local.config.js`
## Como fago eu?

Ben, eu uso [Robo](http://robo.li) para este tipo de tarefas. Concretamente, teño xa un arquivo `RoboFile.php` que contén por defecto o comando `run`, como [se pode ver aqui](https://github.com/fol-project/fol/blob/master/RoboFile.php). Básicamente o que fai é:
- Defino as variables de entorno que quero usar
- Lanzo un servidor web en php apuntando a `/public` e usando `index.php` como frontend controller
- Ao mesmo tempo, lanzo tamén `gulp sync`, e browsersync captura o servidor de php (`localhost:8000`) e sírveo como `localhost:3000`).

Deste xeito, lanzando simplemente `robo run` (ou `robo run -o` para que che abra a paxina no navegador), xa funciona todo.
## Como se faría en laravel?

Dado que laravel ten artisan, igual chega con crear un comando que faga isto. En plan `php artisan run` ou así. Tamén trae o arquivo server.php que serve precisamente para iso.

**Comment by ablunier** [comment]
Grazas @oscarotero, isto en laravel xa se pode facer co comando `php artisan serve` e actualmente nalgún equipo xa traballamos así, pero tendo que lanzar por outro lado o gulp. O que nos quedaría por implementar sería o terceiro punto dos que comentas de como fas ti para poder lanzar só a tarefa gulp que arranque tamén o servidor PHP.

**Comment by ablunier** [comment]
De feito, nun vistazo rápido que acabo de botar penso que sería tan fácil como isto: https://www.npmjs.com/package/laravel-elixir-serve

**Comment by oscarotero** [comment]
Xa supoñía que debería haber algo xa feito. Así cun simple `gulp dev` xa chegaría.
